name: Replicate Issues

on:
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  replicate-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub==1.58

      - name: Replicate Issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.issue.number }}")
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}")
          ISSUE_BODY=$(echo "${{ github.event.issue.body }}")
          ISSUE_STATE=$(echo "${{ github.event.issue.state }}")
          
          ENTERPRISE_REPO="Rajat-Agrawal/test_issue_sync"

          python - <<EOF
          import os
          from github import Github

          print(f"issue number {$ISSUE_NUMBER}")
